// Powered by OnSpace.AI
export const MEAL_TYPES = [
  { id: 'breakfast', label: 'Πρωινό', icon: 'wb-sunny', emoji: '🌅' },
  { id: 'lunch', label: 'Μεσημεριανό', icon: 'restaurant', emoji: '☀️' },
  { id: 'snack', label: 'Σνακ', icon: 'local-cafe', emoji: '🍎' },
  { id: 'dinner', label: 'Βραδινό', icon: 'nights-stay', emoji: '🌙' },
];

export const GOALS = [
  {
    id: 'belly_fat',
    label: 'Απώλεια Κοιλιάς',
    description: 'Καύση λίπους στην κοιλιακή χώρα',
    icon: '🔥',
    dailyCalories: 1600,
    macros: { protein: 35, carbs: 35, fat: 30 },
  },
  {
    id: 'weight_loss',
    label: 'Απώλεια Βάρους',
    description: 'Γενική μείωση σωματικού βάρους',
    icon: '⚡',
    dailyCalories: 1800,
    macros: { protein: 30, carbs: 40, fat: 30 },
  },
  {
    id: 'muscle_gain',
    label: 'Μυϊκή Ανάπτυξη',
    description: 'Χτίσιμο μυϊκής μάζας',
    icon: '💪',
    dailyCalories: 2600,
    macros: { protein: 40, carbs: 40, fat: 20 },
  },
  {
    id: 'healthy_eating',
    label: 'Υγιεινή Διατροφή',
    description: 'Ισορροπημένη διατροφή & ευεξία',
    icon: '🥗',
    dailyCalories: 2000,
    macros: { protein: 25, carbs: 50, fat: 25 },
  },
];

export const MOCK_FOOD_DATABASE: Record<string, any> = {
  pizza: {
    name: 'Πίτσα Μαργαρίτα',
    emoji: '🍕',
    calories: 266,
    protein: 11,
    carbs: 33,
    fat: 10,
    fiber: 2.3,
    sugar: 3.6,
    portionSize: '100g (1 κομμάτι)',
    scores: {
      belly_fat: 2,
      weight_loss: 2,
      muscle_gain: 4,
      healthy_eating: 3,
    },
    alternatives: ['Ολικής αλέσεως πίτα', 'Cauliflower pizza', 'Πίτα με γαλοπούλα'],
  },
  salad: {
    name: 'Χωριάτικη Σαλάτα',
    emoji: '🥗',
    calories: 85,
    protein: 3,
    carbs: 8,
    fat: 5,
    fiber: 2.8,
    sugar: 4.2,
    portionSize: '200g (1 μερίδα)',
    scores: {
      belly_fat: 9,
      weight_loss: 9,
      muscle_gain: 5,
      healthy_eating: 10,
    },
    alternatives: ['Προσθέστε κοτόπουλο', 'Προσθέστε αβοκάντο', 'Quinoa σαλάτα'],
  },
  burger: {
    name: 'Χάμπουργκερ',
    emoji: '🍔',
    calories: 354,
    protein: 20,
    carbs: 29,
    fat: 17,
    fiber: 1.3,
    sugar: 7,
    portionSize: '150g (1 τεμάχιο)',
    scores: {
      belly_fat: 2,
      weight_loss: 2,
      muscle_gain: 6,
      healthy_eating: 2,
    },
    alternatives: ['Lettuce wrap burger', 'Κοτόπουλο ψητό', 'Turkey burger'],
  },
  chicken: {
    name: 'Ψητό Κοτόπουλο',
    emoji: '🍗',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    portionSize: '100g (1 φιλέτο)',
    scores: {
      belly_fat: 9,
      weight_loss: 9,
      muscle_gain: 10,
      healthy_eating: 9,
    },
    alternatives: ['Ψάρι στη σχάρα', 'Γαλοπούλα', 'Τόνος σε νερό'],
  },
  apple: {
    name: 'Μήλο',
    emoji: '🍎',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
    portionSize: '100g (1 μέτριο μήλο)',
    scores: {
      belly_fat: 8,
      weight_loss: 9,
      muscle_gain: 6,
      healthy_eating: 10,
    },
    alternatives: ['Αχλάδι', 'Βερίκοκο', 'Φράουλες'],
  },
  pasta: {
    name: 'Μακαρόνια με σάλτσα',
    emoji: '🍝',
    calories: 220,
    protein: 8,
    carbs: 43,
    fat: 1.5,
    fiber: 2.5,
    sugar: 3,
    portionSize: '200g (1 μερίδα)',
    scores: {
      belly_fat: 3,
      weight_loss: 4,
      muscle_gain: 7,
      healthy_eating: 5,
    },
    alternatives: ['Ολικής αλέσεως ζυμαρικά', 'Zucchini noodles', 'Legume pasta'],
  },
  rice: {
    name: 'Ρύζι με λαχανικά',
    emoji: '🍚',
    calories: 130,
    protein: 3,
    carbs: 28,
    fat: 0.5,
    fiber: 1.8,
    sugar: 0.5,
    portionSize: '150g (1 μερίδα)',
    scores: {
      belly_fat: 5,
      weight_loss: 6,
      muscle_gain: 7,
      healthy_eating: 7,
    },
    alternatives: ['Καστανό ρύζι', 'Quinoa', 'Κριθάρι'],
  },
  eggs: {
    name: 'Αυγά Ομελέτα',
    emoji: '🍳',
    calories: 154,
    protein: 11,
    carbs: 1.6,
    fat: 11,
    fiber: 0,
    sugar: 0.8,
    portionSize: '2 αυγά (100g)',
    scores: {
      belly_fat: 7,
      weight_loss: 7,
      muscle_gain: 9,
      healthy_eating: 8,
    },
    alternatives: ['Scrambled egg whites', 'Ομελέτα με λαχανικά', 'Βραστά αυγά'],
  },
};

export const SCAN_KEYWORDS: Record<string, string> = {
  pizza: 'pizza',
  πίτσα: 'pizza',
  salad: 'salad',
  σαλάτα: 'salad',
  burger: 'burger',
  χάμπουργκερ: 'burger',
  chicken: 'chicken',
  κοτόπουλο: 'chicken',
  apple: 'apple',
  μήλο: 'apple',
  pasta: 'pasta',
  μακαρόνια: 'pasta',
  rice: 'rice',
  ρύζι: 'rice',
  eggs: 'eggs',
  αυγά: 'eggs',
};
